os: linux
dist: bionic
language: cpp

addons:
  apt:
    update: true
    packages:
      - clang-10
      - llvm-10
      - llvm-10-dev
      - cmake
      - libclang-10-dev
      - libclang-common-10-dev

script:
  - mkdir build
  - cd build
  - CC=clang-10 CXX=clang++-10 cmake -G "Unix Makefiles"  ..
  - make
  - ctest --debug
  - cpack