os: linux
dist: focal
language: cpp

addons:
  apt:
    update: true
    packages:
      - clang-13
      - llvm-13
      - llvm-13-dev
      - cmake
      - libclang-13-dev
      - libclang-common-13-dev
    sources:
      - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

script:
  - mkdir build
  - cd build
  - LLVM_DIR=/usr/lib/llvm-13 CC=clang-13 CXX=clang++-13 cmake -G "Unix Makefiles"  ..
  - make
  - make test
  - cpack