os: linux
dist: focal
language: cpp

addons:
  apt:
    update: true
    packages:
      - clang-11
      - llvm-11
      - llvm-11-dev
      - cmake
      - libclang-11-dev
      - libclang-common-11-dev
    sources:
      - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

script:
  - mkdir build
  - cd build
  - LLVM_DIR=/usr/lib/llvm-11 CC=clang-11 CXX=clang++-11 cmake -G "Unix Makefiles"  ..
  - make
  - make test
  - cpack