os: linux
dist: bionic
language: cpp

addons:
  apt:
    update: true
    packages:
      - clang-10
      - clang-10-dev
      - llvm-10
      - llvm-10-dev
      - cmake

script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles"  ..
  - make
  - make test
  - cpack